REQUIRED_SKILL_WEIGHT = 0.55
PREFERRED_SKILL_WEIGHT = 0.15
YEARS_EXPERIENCE_WEIGHT = 0.15
WORK_AUTHORIZATION_WEIGHT = 0.10
LOCATION_WEIGHT = 0.05

SUBMIT_SCORE_THRESHOLD = 80.0
SUBMIT_MIN_YEARS_SCORE = 80.0

REVIEW_SCORE_THRESHOLD = 60.0
REVIEW_MIN_REQUIRED_SKILL_SCORE = 60.0

MATCHER_VERSION = "basic_local_matcher_v1"
