from app.engineering_memory.models import DailyEngineeringMemory


def render_list(items: list[str]) -> str:
    if not items:
        return "- None"

    return "\n".join([f"- {item}" for item in items])


def render_decisions(memory: DailyEngineeringMemory) -> str:
    if not memory.decisions:
        return "- None"

    lines = []

    for decision in memory.decisions:
        prefix = f"{decision.id} - " if decision.id else ""
        lines.append(f"- {prefix}{decision.title} ({decision.status})")
        lines.append(f"  - {decision.summary}")

    return "\n".join(lines)


def render_incidents(memory: DailyEngineeringMemory) -> str:
    if not memory.incidents:
        return "- None"

    lines = []

    for incident in memory.incidents:
        prefix = f"{incident.id} - " if incident.id else ""
        lines.append(f"- {prefix}{incident.title}")
        lines.append(f"  - Summary: {incident.summary}")
        lines.append(f"  - Resolution: {incident.resolution}")

        if incident.root_cause:
            lines.append(f"  - Root Cause: {incident.root_cause}")

        if incident.prevention:
            lines.append(f"  - Prevention: {incident.prevention}")

    return "\n".join(lines)


def render_daily_memory(memory: DailyEngineeringMemory) -> str:
    return f"""# Engineering Memory

Date: {memory.date}

Status: {memory.status}

---

# Executive Summary

{memory.summary}

---

# Repositories

{render_list(memory.repositories)}

---

# Completed Today

{render_list(memory.completed)}

---

# Architecture Decisions

{render_decisions(memory)}

---

# Incidents

{render_incidents(memory)}

---

# Lessons Learned

{render_list(memory.lessons_learned)}

---

# Open Items

{render_list(memory.open_items)}

---

# Tomorrow

{memory.tomorrow_objective}

---

Generated by Hermes Engineering Memory Engine
"""