"""Reviewed glossary enrichment for the most requested staffing skills.

This is the canonical, human-reviewed source for `short_definition`, `recruiter_explanation`, `subcategory`,
`related_roles` and typed `relationships`. The backfill script applies it to a taxonomy file, and existing human-authored
values always win. Skills are keyed by their canonical taxonomy name.

Relationship types are a small controlled vocabulary. A relationship is context, never equivalence: a related skill must not
be counted as a match for a required one.
"""

from __future__ import annotations

RELATIONSHIP_TYPES = frozenset(
    {
        "commonly_used_with",
        "framework_for",
        "managed_service_for",
        "builds_on",
        "runs_on",
    }
)

# A category that says nothing (the bulk of the imported tail). Enrichment may replace these, and only these.
GENERIC_CATEGORIES = frozenset({"", "Tool/Technology", "Uncategorized"})


def _skill(subcategory, definition, recruiter, roles, relationships=(), category=None):
    row = {
        "subcategory": subcategory,
        "short_definition": definition,
        "recruiter_explanation": recruiter,
        "related_roles": list(roles),
    }
    if relationships:
        row["relationships"] = [{"type": kind, "skill": name} for kind, name in relationships]
    if category:
        row["category"] = category
    return row


ENRICHMENT: dict[str, dict] = {
    # --- Containers, cloud and DevOps ---
    "Kubernetes": _skill(
        "Container Orchestration",
        "Container orchestration platform for deploying, scaling, and operating containerized applications.",
        "Common in DevOps, SRE, cloud, and platform roles; often requested with Docker, Helm, Terraform, and a cloud provider.",
        ["DevOps Engineer", "Site Reliability Engineer", "Platform Engineer", "Cloud Engineer"],
        [("commonly_used_with", "Docker"), ("commonly_used_with", "Helm"), ("commonly_used_with", "Terraform")],
    ),
    "Docker": _skill(
        "Containers",
        "Platform and tooling for packaging and running applications in containers.",
        "Common across software, DevOps, and platform roles and frequently paired with Kubernetes and CI/CD.",
        ["DevOps Engineer", "Platform Engineer", "Software Engineer"],
        [("commonly_used_with", "Kubernetes")],
    ),
    "Helm": _skill(
        "Container Orchestration",
        "Package manager for Kubernetes that bundles application configuration into reusable charts.",
        "Seen in Kubernetes-heavy DevOps and platform roles; usually a sign of hands-on cluster deployment work.",
        ["DevOps Engineer", "Platform Engineer", "Site Reliability Engineer"],
        [("commonly_used_with", "Kubernetes")],
    ),
    "OpenShift": _skill(
        "Container Platform",
        "Red Hat's enterprise Kubernetes platform with added developer and operations tooling.",
        "Requested in large enterprises and regulated industries that run Kubernetes on Red Hat; usually needs Kubernetes fundamentals.",
        ["DevOps Engineer", "Platform Engineer", "Cloud Engineer"],
        [("builds_on", "Kubernetes")],
    ),
    "EKS": _skill(
        "Container Orchestration",
        "Amazon's managed Kubernetes service.",
        "Signals Kubernetes experience on AWS; confirm cluster operations versus application deployment.",
        ["DevOps Engineer", "Cloud Engineer", "Platform Engineer"],
        [("managed_service_for", "Kubernetes"), ("runs_on", "AWS")],
    ),
    "AKS": _skill(
        "Container Orchestration",
        "Microsoft Azure's managed Kubernetes service.",
        "Signals Kubernetes experience on Azure; common in Microsoft-centric enterprises.",
        ["DevOps Engineer", "Cloud Engineer", "Platform Engineer"],
        [("managed_service_for", "Kubernetes"), ("runs_on", "Azure")],
    ),
    "Terraform": _skill(
        "Infrastructure as Code",
        "Tool for defining and provisioning cloud infrastructure from declarative configuration files.",
        "Core requirement for DevOps, cloud, and platform roles; usually paired with AWS, Azure, or GCP and CI/CD pipelines.",
        ["DevOps Engineer", "Cloud Engineer", "Platform Engineer"],
        [("commonly_used_with", "AWS"), ("commonly_used_with", "Azure")],
    ),
    "Ansible": _skill(
        "Configuration Management",
        "Agentless automation tool for configuring servers and deploying applications.",
        "Common in DevOps and systems roles, often alongside Linux administration and Terraform.",
        ["DevOps Engineer", "Systems Engineer", "Site Reliability Engineer"],
        [("commonly_used_with", "Terraform")],
    ),
    "Jenkins": _skill(
        "CI/CD",
        "Open-source automation server for building, testing, and deploying software.",
        "Very common CI/CD requirement in enterprise DevOps and QA automation roles.",
        ["DevOps Engineer", "Build Engineer", "QA Automation Engineer"],
        [("commonly_used_with", "Docker"), ("commonly_used_with", "Git")],
    ),
    "GitHub Actions": _skill(
        "CI/CD",
        "Workflow automation built into GitHub for building, testing, and deploying code.",
        "Common in teams hosted on GitHub; a modern alternative on resumes to Jenkins-style pipelines.",
        ["DevOps Engineer", "Software Engineer", "Platform Engineer"],
        [("commonly_used_with", "Git")],
    ),
    "GitLab CI": _skill(
        "CI/CD",
        "Continuous integration and delivery pipelines built into GitLab.",
        "Seen in teams that host code on GitLab; expect pipeline authoring and runner configuration.",
        ["DevOps Engineer", "Software Engineer", "Build Engineer"],
        [("commonly_used_with", "Git")],
    ),
    "Azure DevOps": _skill(
        "CI/CD",
        "Microsoft's suite for source control, pipelines, boards, and artifact management.",
        "Common in Microsoft and .NET shops; often requested with Azure and C#.",
        ["DevOps Engineer", ".NET Developer", "Cloud Engineer"],
        [("runs_on", "Azure")],
    ),
    "Git": _skill(
        "Version Control",
        "Distributed version control system for tracking source code changes.",
        "Assumed for nearly every engineering role; rarely a differentiator on its own.",
        ["Software Engineer", "DevOps Engineer", "Developer"],
        category="DevOps",
    ),
    "Jira": _skill(
        "Work Management",
        "Issue and project tracking tool widely used by agile software teams.",
        "Usually a baseline expectation for developers and QA; a stronger signal for project and scrum roles.",
        ["Scrum Master", "Project Manager", "QA Engineer"],
        [("commonly_used_with", "Agile")],
        category="Project Management",
    ),
    "Prometheus": _skill(
        "Observability",
        "Open-source monitoring system that collects and queries time-series metrics.",
        "Common in SRE and Kubernetes environments, usually paired with Grafana.",
        ["Site Reliability Engineer", "DevOps Engineer", "Platform Engineer"],
        [("commonly_used_with", "Grafana"), ("commonly_used_with", "Kubernetes")],
        category="DevOps",
    ),
    "Grafana": _skill(
        "Observability",
        "Dashboarding tool for visualizing metrics and logs from many data sources.",
        "Seen in SRE and DevOps roles, typically together with Prometheus.",
        ["Site Reliability Engineer", "DevOps Engineer"],
        [("commonly_used_with", "Prometheus")],
        category="DevOps",
    ),
    "Datadog": _skill(
        "Observability",
        "Commercial monitoring and analytics platform for infrastructure, applications, and logs.",
        "Requested in cloud-native teams that need monitoring and incident response experience.",
        ["Site Reliability Engineer", "DevOps Engineer", "Cloud Engineer"],
        category="DevOps",
    ),
    "Splunk": _skill(
        "Log Analytics",
        "Platform for searching, monitoring, and analyzing machine-generated data and logs.",
        "Common in operations and security roles; confirm whether the need is administration, dashboards, or SIEM use.",
        ["Splunk Engineer", "Security Analyst", "Site Reliability Engineer"],
        category="DevOps",
    ),
    "AWS": _skill(
        "Cloud Platform",
        "Amazon Web Services cloud platform for compute, storage, networking, data, and managed services.",
        "Broad cloud experience signal; confirm which AWS services and whether the role expects architecture, development, operations, or security depth.",
        ["Cloud Engineer", "DevOps Engineer", "Solutions Architect"],
    ),
    "Azure": _skill(
        "Cloud Platform",
        "Microsoft's cloud platform for compute, storage, networking, data, and managed services.",
        "Common in Microsoft-centric enterprises; confirm the services and whether the role is development, operations, or architecture.",
        ["Cloud Engineer", "DevOps Engineer", "Solutions Architect"],
    ),
    "GCP": _skill(
        "Cloud Platform",
        "Google Cloud Platform for compute, storage, data analytics, and machine learning services.",
        "Less common than AWS or Azure; frequently tied to data engineering and machine learning roles.",
        ["Cloud Engineer", "Data Engineer", "DevOps Engineer"],
    ),
    "AWS Lambda": _skill(
        "Serverless",
        "Amazon's serverless compute service that runs code in response to events.",
        "Seen in event-driven and serverless backend roles; usually alongside API Gateway, S3, and DynamoDB.",
        ["Cloud Engineer", "Backend Engineer", "Serverless Developer"],
        [("runs_on", "AWS")],
    ),
    # --- Languages and frameworks ---
    "Java": _skill(
        "Programming Language",
        "General-purpose, object-oriented language widely used for enterprise back-end systems.",
        "A staple of enterprise and financial-services hiring; usually paired with Spring Boot, microservices, and SQL.",
        ["Java Developer", "Backend Engineer", "Software Engineer"],
        [("commonly_used_with", "Spring Boot")],
    ),
    "Spring Boot": _skill(
        "Backend Framework",
        "Java framework for building production-ready web services and applications.",
        "A core backend skill for Java developers, commonly paired with microservices, REST APIs, SQL databases, and cloud platforms.",
        ["Java Developer", "Backend Engineer", "Software Engineer"],
        [("framework_for", "Java")],
    ),
    "Hibernate": _skill(
        "Persistence Framework",
        "Java object-relational mapping framework that maps objects to database tables.",
        "Appears in Java enterprise requirements next to Spring and SQL; usually a supporting skill.",
        ["Java Developer", "Backend Engineer"],
        [("framework_for", "Java")],
    ),
    "Python": _skill(
        "Programming Language",
        "General-purpose language popular for web back ends, automation, data engineering, and machine learning.",
        "Requested across backend, data, and automation roles; confirm the context, since the same word covers very different jobs.",
        ["Python Developer", "Data Engineer", "Backend Engineer"],
    ),
    "Django": _skill(
        "Backend Framework",
        "Full-featured Python web framework.",
        "Common in Python web roles; often requested with PostgreSQL and REST APIs.",
        ["Python Developer", "Backend Engineer", "Full Stack Developer"],
        [("framework_for", "Python"), ("commonly_used_with", "PostgreSQL")],
    ),
    "Flask": _skill(
        "Backend Framework",
        "Lightweight Python web framework for APIs and small services.",
        "Seen in Python API and microservice roles.",
        ["Python Developer", "Backend Engineer"],
        [("framework_for", "Python")],
    ),
    "FastAPI": _skill(
        "Backend Framework",
        "Modern Python framework for building typed, high-performance APIs.",
        "Increasingly requested for Python API and machine-learning service roles.",
        ["Python Developer", "Backend Engineer", "Machine Learning Engineer"],
        [("framework_for", "Python")],
    ),
    "JavaScript": _skill(
        "Programming Language",
        "Language of the web, used in browsers and, through Node.js, on servers.",
        "Baseline for frontend and full-stack roles; ask which frameworks the team uses.",
        ["Frontend Developer", "Full Stack Developer", "JavaScript Developer"],
    ),
    "TypeScript": _skill(
        "Programming Language",
        "Typed superset of JavaScript that compiles to plain JavaScript.",
        "Now standard for serious frontend and Node.js work; usually requested with React or Angular.",
        ["Frontend Developer", "Full Stack Developer", "Node.js Developer"],
        [("builds_on", "JavaScript"), ("commonly_used_with", "React")],
    ),
    "React": _skill(
        "Web UI Library",
        "JavaScript library for building component-based user interfaces.",
        "A common frontend requirement, frequently paired with JavaScript or TypeScript, state management, and modern web tooling.",
        ["Frontend Developer", "Full Stack Developer", "UI Engineer"],
        [("commonly_used_with", "TypeScript")],
    ),
    "Angular": _skill(
        "Web UI Framework",
        "Google's TypeScript framework for building large single-page applications.",
        "Common in enterprise frontend roles; strongly tied to TypeScript.",
        ["Frontend Developer", "Full Stack Developer", "UI Engineer"],
        [("builds_on", "TypeScript")],
    ),
    "Vue.js": _skill(
        "Web UI Framework",
        "Progressive JavaScript framework for building user interfaces.",
        "Seen in frontend roles at smaller product teams; less common in enterprise staffing than React or Angular.",
        ["Frontend Developer", "Full Stack Developer"],
        [("builds_on", "JavaScript")],
    ),
    "Node.js": _skill(
        "JavaScript Runtime",
        "Server-side JavaScript runtime built on the V8 engine.",
        "Common for backend and full-stack JavaScript roles, often paired with TypeScript, REST APIs, and cloud services.",
        ["Backend Engineer", "Full Stack Developer", "JavaScript Developer"],
        [("runs_on", "JavaScript"), ("commonly_used_with", "TypeScript")],
    ),
    "Express.js": _skill(
        "Backend Framework",
        "Minimal web framework for Node.js.",
        "Standard choice in Node.js API roles.",
        ["Backend Engineer", "Full Stack Developer"],
        [("framework_for", "Node.js")],
    ),
    "C#": _skill(
        "Programming Language",
        "Microsoft's object-oriented language, used mainly on the .NET platform.",
        "Core requirement for .NET developer roles; usually paired with ASP.NET, SQL Server, and Azure.",
        [".NET Developer", "Backend Engineer", "Software Engineer"],
        [("commonly_used_with", ".NET")],
    ),
    ".NET": _skill(
        "Application Platform",
        "Microsoft's platform for building web, desktop, and cloud applications, mainly in C#.",
        "Requested across enterprise back-end roles; check whether legacy .NET Framework or modern .NET Core is meant.",
        [".NET Developer", "Backend Engineer", "Full Stack Developer"],
        [("commonly_used_with", "C#"), ("commonly_used_with", "SQL Server")],
        category="Backend",
    ),
    "Go": _skill(
        "Programming Language",
        "Compiled language from Google designed for simple, fast, concurrent services.",
        "Seen in cloud-native and infrastructure roles; the name often appears as Golang on job posts.",
        ["Backend Engineer", "Platform Engineer", "Site Reliability Engineer"],
    ),
    "Scala": _skill(
        "Programming Language",
        "JVM language combining object-oriented and functional programming.",
        "Mostly requested in data engineering roles that use Apache Spark.",
        ["Data Engineer", "Backend Engineer"],
        [("commonly_used_with", "Apache Spark")],
    ),
    "Kotlin": _skill(
        "Programming Language",
        "Modern JVM language, the preferred language for Android development.",
        "Requested for Android roles and, less often, Spring back ends.",
        ["Android Developer", "Mobile Developer", "Backend Engineer"],
    ),
    "Swift": _skill(
        "Programming Language",
        "Apple's language for iOS, macOS, and other Apple platforms.",
        "Required for native iOS roles.",
        ["iOS Developer", "Mobile Developer"],
    ),
    "PHP": _skill(
        "Programming Language",
        "Server-side scripting language behind many websites and content platforms.",
        "Common in web agencies and e-commerce; often requested with Laravel and MySQL.",
        ["PHP Developer", "Full Stack Developer", "Web Developer"],
    ),
    "Ruby on Rails": _skill(
        "Backend Framework",
        "Convention-driven web framework for the Ruby language.",
        "Found at product startups and long-lived Rails codebases; a smaller talent pool.",
        ["Ruby Developer", "Backend Engineer", "Full Stack Developer"],
    ),
    "React Native": _skill(
        "Mobile Framework",
        "Framework for building iOS and Android apps with React and JavaScript.",
        "Requested when one team ships to both mobile platforms; usually needs solid React experience.",
        ["Mobile Developer", "Frontend Developer"],
        [("builds_on", "React")],
        category="Mobile",
    ),
    "Flutter": _skill(
        "Mobile Framework",
        "Google's toolkit for building cross-platform apps in the Dart language.",
        "Growing requirement for cross-platform mobile roles.",
        ["Mobile Developer"],
        category="Mobile",
    ),
    # --- APIs, architecture, data ---
    "REST API": _skill(
        "API Design",
        "Architectural style for web services that expose resources over HTTP.",
        "A baseline for backend and integration roles; usually not a standalone requirement.",
        ["Backend Engineer", "Integration Engineer", "Software Engineer"],
    ),
    "GraphQL": _skill(
        "API Design",
        "Query language and runtime that lets clients request exactly the data they need.",
        "Seen in modern frontend-heavy products; usually requested next to React and Node.js.",
        ["Backend Engineer", "Full Stack Developer", "Frontend Developer"],
    ),
    "Microservices": _skill(
        "Architecture",
        "Architecture style that builds an application from small, independently deployable services.",
        "Frequently paired with Spring Boot, Docker, Kubernetes, and messaging; check the team's actual scale.",
        ["Backend Engineer", "Software Architect", "Java Developer"],
        [("commonly_used_with", "Docker"), ("commonly_used_with", "Kafka")],
    ),
    "Kafka": _skill(
        "Event Streaming",
        "Distributed event-streaming platform for high-throughput data pipelines and real-time applications.",
        "Often required in backend and data roles involving event-driven architecture, messaging, and streaming systems.",
        ["Backend Engineer", "Data Engineer", "Streaming Engineer"],
        [("commonly_used_with", "Microservices")],
    ),
    "RabbitMQ": _skill(
        "Message Broker",
        "Open-source message broker for asynchronous communication between services.",
        "Seen in service-oriented back ends; a lighter-weight messaging option than Kafka.",
        ["Backend Engineer", "Integration Engineer"],
    ),
    "SQL": _skill(
        "Query Language",
        "Standard language for querying and managing relational databases.",
        "Baseline for backend, data, and analyst roles; ask which database and how complex the queries are.",
        ["Data Analyst", "Backend Engineer", "Database Developer"],
        category="Database",
    ),
    "PostgreSQL": _skill(
        "Relational Database",
        "Open-source relational database known for standards compliance and extensibility.",
        "Requested across backend, data, and platform roles where production SQL and relational data modeling matter.",
        ["Backend Engineer", "Data Engineer", "Database Administrator"],
    ),
    "MySQL": _skill(
        "Relational Database",
        "Popular open-source relational database, common in web applications.",
        "Common in web and e-commerce back ends, often with PHP.",
        ["Backend Engineer", "Database Administrator", "PHP Developer"],
    ),
    "SQL Server": _skill(
        "Relational Database",
        "Microsoft's relational database, common in .NET and enterprise environments.",
        "Typically paired with C# and .NET; also requested for BI and DBA roles.",
        ["Database Administrator", ".NET Developer", "BI Developer"],
    ),
    "MongoDB": _skill(
        "Document Database",
        "Document-oriented NoSQL database that stores JSON-like records.",
        "Common in Node.js and rapid-development back ends.",
        ["Backend Engineer", "Full Stack Developer"],
    ),
    "Redis": _skill(
        "In-Memory Data Store",
        "In-memory data store used for caching, queues, and fast lookups.",
        "Usually a supporting skill in backend roles focused on performance.",
        ["Backend Engineer", "Platform Engineer"],
    ),
    "Elasticsearch": _skill(
        "Search Engine",
        "Distributed search and analytics engine built on Lucene.",
        "Requested for search and log analytics roles, often as part of the ELK stack.",
        ["Backend Engineer", "Search Engineer", "Data Engineer"],
    ),
    "Snowflake": _skill(
        "Cloud Data Warehouse",
        "Cloud data warehouse platform for analytics and data sharing.",
        "Hot requirement for data engineering and analytics roles; often paired with SQL, dbt, and Python.",
        ["Data Engineer", "Analytics Engineer", "Data Architect"],
        [("commonly_used_with", "SQL")],
    ),
    "Databricks": _skill(
        "Data Platform",
        "Cloud platform for data engineering, analytics, and machine learning built around Apache Spark.",
        "Common in data engineering and ML roles; usually needs Spark and Python or Scala.",
        ["Data Engineer", "Machine Learning Engineer", "Data Scientist"],
        [("builds_on", "Apache Spark")],
    ),
    "Apache Spark": _skill(
        "Big Data Processing",
        "Distributed engine for large-scale data processing and analytics.",
        "Core big-data requirement; commonly with Python or Scala, Hadoop, and cloud storage.",
        ["Data Engineer", "Big Data Engineer"],
        [("commonly_used_with", "Scala"), ("commonly_used_with", "Python")],
    ),
    "Hadoop": _skill(
        "Big Data Processing",
        "Framework for distributed storage and processing of very large datasets.",
        "Mostly legacy big-data environments; newer roles favor Spark and cloud data platforms.",
        ["Big Data Engineer", "Data Engineer"],
    ),
    "ETL": _skill(
        "Data Integration",
        "Extract, transform, load: moving and reshaping data between systems.",
        "Generic data-integration requirement; ask which tools (Informatica, Talend, SSIS) the team uses.",
        ["ETL Developer", "Data Engineer"],
        [("commonly_used_with", "SQL")],
        category="Data Engineering",
    ),
    "Informatica": _skill(
        "Data Integration",
        "Enterprise data-integration and ETL platform.",
        "Long-standing enterprise ETL requirement in banking, insurance, and healthcare.",
        ["ETL Developer", "Data Engineer"],
        category="Data Engineering",
    ),
    "Talend": _skill(
        "Data Integration",
        "Data-integration platform with open-source and enterprise editions.",
        "Seen in ETL roles as an alternative to Informatica.",
        ["ETL Developer", "Data Engineer"],
        category="Data Engineering",
    ),
    "MuleSoft": _skill(
        "Integration Platform",
        "Enterprise integration platform for connecting applications and APIs.",
        "Common in Salesforce-adjacent enterprises for API-led integration.",
        ["Integration Developer", "API Developer"],
        [("commonly_used_with", "Salesforce")],
        category="Integration",
    ),
    "Power BI": _skill(
        "Business Intelligence",
        "Microsoft's business-intelligence tool for dashboards and reports.",
        "Very common in analytics roles at Microsoft-centric companies; usually with SQL and DAX.",
        ["BI Developer", "Data Analyst"],
        [("commonly_used_with", "SQL Server")],
        category="BI",
    ),
    "Tableau": _skill(
        "Business Intelligence",
        "Data-visualization platform for interactive dashboards.",
        "Standard requirement for BI and analytics roles.",
        ["BI Developer", "Data Analyst"],
        category="BI",
    ),
    # --- AI / ML ---
    "Machine Learning": _skill(
        "AI Discipline",
        "Building models that learn patterns from data to make predictions.",
        "Broad term; ask which frameworks, model types, and whether the role is research or production engineering.",
        ["Machine Learning Engineer", "Data Scientist"],
        [("commonly_used_with", "Python")],
        category="AI",
    ),
    "TensorFlow": _skill(
        "Deep Learning Framework",
        "Google's open-source framework for building and deploying machine-learning models.",
        "Requested for deep-learning roles; PyTorch is now more common in new work.",
        ["Machine Learning Engineer", "Data Scientist"],
        [("framework_for", "Machine Learning")],
        category="AI",
    ),
    "PyTorch": _skill(
        "Deep Learning Framework",
        "Open-source deep-learning framework popular in research and production.",
        "Frequently requested for machine-learning and generative-AI roles.",
        ["Machine Learning Engineer", "Data Scientist", "AI Engineer"],
        [("framework_for", "Machine Learning")],
        category="AI",
    ),
    "Pandas": _skill(
        "Data Analysis Library",
        "Python library for data manipulation and analysis.",
        "Assumed for data analyst and data science roles that use Python.",
        ["Data Scientist", "Data Analyst", "Data Engineer"],
        [("builds_on", "Python")],
        category="Data Science",
    ),
    # --- Enterprise platforms ---
    "Salesforce": _skill(
        "CRM Platform",
        "Cloud CRM platform for sales, service, and marketing, extensible with Apex and Lightning.",
        "Large, specialized talent pool; confirm admin, developer, or architect scope and which clouds.",
        ["Salesforce Developer", "Salesforce Administrator", "Salesforce Architect"],
        category="CRM",
    ),
    "ServiceNow": _skill(
        "ITSM Platform",
        "Cloud platform for IT service management and enterprise workflow automation.",
        "High-demand enterprise skill; confirm developer, admin, or architect and which modules.",
        ["ServiceNow Developer", "ServiceNow Administrator"],
        category="ITSM",
    ),
    "SAP": _skill(
        "ERP Platform",
        "Enterprise resource planning software for finance, supply chain, and operations.",
        "Always ask which SAP module (FICO, MM, SD, HANA, ABAP); the label alone is too broad to match on.",
        ["SAP Consultant", "SAP Developer", "SAP Analyst"],
        category="ERP",
    ),
    "Workday": _skill(
        "HCM Platform",
        "Cloud platform for human capital management and financials.",
        "Specialized functional and integration skill; confirm HCM, payroll, or Financials and Studio experience.",
        ["Workday Consultant", "Workday Analyst", "Workday Integration Developer"],
        category="HCM",
    ),
    "Okta": _skill(
        "Identity Management",
        "Cloud identity platform for single sign-on and access management.",
        "Requested in security and IAM roles.",
        ["IAM Engineer", "Security Engineer"],
        category="Security",
    ),
    # --- Testing and process ---
    "Selenium": _skill(
        "Test Automation",
        "Framework for automating web browsers in functional tests.",
        "Long-standing QA automation requirement, usually with Java or Python.",
        ["QA Automation Engineer", "SDET"],
        category="Testing",
    ),
    "Cypress": _skill(
        "Test Automation",
        "JavaScript end-to-end testing framework for web applications.",
        "Common in modern frontend QA automation roles.",
        ["QA Automation Engineer", "SDET", "Frontend Developer"],
        category="Testing",
    ),
    "Playwright": _skill(
        "Test Automation",
        "Cross-browser end-to-end testing framework from Microsoft.",
        "Rising requirement in QA automation, often replacing Selenium in new projects.",
        ["QA Automation Engineer", "SDET"],
        category="Testing",
    ),
    "JUnit": _skill(
        "Unit Testing",
        "Standard unit-testing framework for Java.",
        "Assumed for Java developers; appears in QA and SDET requirements too.",
        ["Java Developer", "SDET"],
        [("framework_for", "Java")],
        category="Testing",
    ),
    "Agile": _skill(
        "Delivery Methodology",
        "Iterative approach to software delivery built on short cycles and frequent feedback.",
        "Near-universal on job posts; only meaningful as a differentiator for project and scrum roles.",
        ["Scrum Master", "Project Manager", "Product Owner"],
        [("commonly_used_with", "Scrum")],
        category="Methodology",
    ),
    "Scrum": _skill(
        "Delivery Methodology",
        "Agile framework organized around sprints, defined roles, and regular ceremonies.",
        "Core for Scrum Master and Product Owner roles; certification (CSM, PSM) is a common ask.",
        ["Scrum Master", "Product Owner", "Project Manager"],
        [("builds_on", "Agile")],
        category="Methodology",
    ),
}
